export const  ObjChannelCommission = 
	  {
    "Channel Expenses": [
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Expedia",
            "Transaction": "EX101",
            "AccDate": "20-Nov-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "399.46",
            "ExpAmntWthtoutVat": "399.46",
            "TtlPmnt": "0",
            "BlncExp": "399.46",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "asd",
            "RC": "RC61"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX109",
            "AccDate": "30-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "111.11",
            "ExpAmntWthtoutVat": "111.11",
            "TtlPmnt": "10.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC74"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX111",
            "AccDate": "30-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "111.11",
            "ExpAmntWthtoutVat": "111.11",
            "TtlPmnt": "10",
            "BlncExp": "101.11",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC76"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX113",
            "AccDate": "30-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "111.11",
            "ExpAmntWthtoutVat": "111.11",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC77"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX115",
            "AccDate": "21-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "0",
            "ExpAmntWthtoutVat": "0",
            "TtlPmnt": "0",
            "BlncExp": "100",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "gogo1",
            "RC": "RC40"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX122",
            "AccDate": "10-Dec-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "26038.11",
            "ExpAmntWthtoutVat": "26038.11",
            "TtlPmnt": "0",
            "BlncExp": "26038.11",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "aaass",
            "RC": "RC108_7f0a2551-f8f9-4087-87a1-f4289a47fdb4"
        },
        {
            "LstSave": "03-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Agoda",
            "Transaction": "EX124",
            "AccDate": "16-Dec-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "162515.29",
            "ExpAmntWthtoutVat": "162515.29",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "fg",
            "RC": "RC109_7c447bca-7bed-4824-83d4-840be1e47fa2"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX126_5fccc18a-3259-4e4a-bf7d-fd241de0d2c8",
            "AccDate": "09-Dec-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "13717.33",
            "ExpAmntWthtoutVat": "13717.33",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "zzzz",
            "RC": "RC110_72fdc530-9c7c-4f84-9682-c4aaf6f5b030"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX137_b432af32-1bbe-424d-ae11-4d42e46d2d57",
            "AccDate": "04-Feb-2020",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "111.11",
            "ExpAmntWthtoutVat": "111.11",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "testnow",
            "RC": "RC113_d69ebbe9-c256-4abd-a2cd-022d942d8bc6"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Booking",
            "Transaction": "EX139_beab3c76-9e81-4293-af4c-bf966f363a0a",
            "AccDate": "05-Dec-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "25.53",
            "ExpAmntWthtoutVat": "25.53",
            "TtlPmnt": "0",
            "BlncExp": "25.53",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "h",
            "RC": "RC114_db240972-7a11-45ff-a1bf-fdb44a7ed57d"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX142_0a26cb60-86e8-4e71-830d-3f6efba62181",
            "AccDate": "13-Dec-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "111.11",
            "ExpAmntWthtoutVat": "111.11",
            "TtlPmnt": "111.11",
            "BlncExp": "0",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "idan Lavy",
            "RC": "RC115_a11c1b03-3717-4ce9-8a4b-7396c8d69a72"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX144_ab05544a-290e-4a7d-8d95-d521296f6cef",
            "AccDate": "10-Dec-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "1111.11",
            "ExpAmntWthtoutVat": "1111.11",
            "TtlPmnt": "1000",
            "BlncExp": "111.11",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "fgfg",
            "RC": "RC117_926b7d87-3a25-47ab-b25c-4e265fc832ab"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX146_4f0cbc37-3ae9-44fe-9bac-387dab786f8d",
            "AccDate": "01-Jan-2020",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "111.11",
            "ExpAmntWthtoutVat": "111.11",
            "TtlPmnt": "111.11",
            "BlncExp": "0",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST111",
            "RC": "RC118_aa122989-3e21-48f4-9434-9c0b1acb2ae5"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Booking",
            "Transaction": "EX148_09d47a20-c9b8-4322-b864-a3a67ae38dee",
            "AccDate": "23-Dec-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "102.04",
            "ExpAmntWthtoutVat": "102.04",
            "TtlPmnt": "100",
            "BlncExp": "2.04",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST2",
            "RC": "RC119_79fa8649-5730-48dd-ae21-aa9f6bea6b11"
        },
        {
            "LstSave": "01-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Booking",
            "Transaction": "EX33",
            "AccDate": "06-Nov-2019",
            "PrpName": "idanprop3",
            "AptName": "Idanprop3 Apartment",
            "Amnt": "20.41",
            "ExpAmntWthtoutVat": "20.41",
            "TtlPmnt": "20.41",
            "BlncExp": "0",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST 1",
            "RC": "RC21"
        },
        {
            "LstSave": "01-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Agoda",
            "Transaction": "EX53",
            "AccDate": "12-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "58096.94",
            "ExpAmntWthtoutVat": "58096.94",
            "TtlPmnt": "0",
            "BlncExp": "58096.94",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "test3",
            "RC": "RC32"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Flipkey",
            "Transaction": "EX60",
            "AccDate": "26-Nov-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "1148.62",
            "ExpAmntWthtoutVat": "1148.62",
            "TtlPmnt": "0",
            "BlncExp": "1148.62",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "test345",
            "RC": "RC38"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Agoda",
            "Transaction": "EX62",
            "AccDate": "18-Nov-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "26090.82",
            "ExpAmntWthtoutVat": "26090.82",
            "TtlPmnt": "0",
            "BlncExp": "26090.82",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "zzzz",
            "RC": "RC39"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Expedia",
            "Transaction": "EX69",
            "AccDate": "27-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "12.36",
            "ExpAmntWthtoutVat": "12.36",
            "TtlPmnt": "0",
            "BlncExp": "12.36",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "Alanna Culingham",
            "RC": "RC43"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Booking",
            "Transaction": "EX76",
            "AccDate": "03-Dec-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "20.41",
            "ExpAmntWthtoutVat": "20.41",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC48"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Booking",
            "Transaction": "EX82",
            "AccDate": "15-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "102.04",
            "ExpAmntWthtoutVat": "102.04",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC51"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Booking",
            "Transaction": "EX83",
            "AccDate": "29-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "2040.82",
            "ExpAmntWthtoutVat": "2040.82",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC52"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Channel advance commission",
            "vendor": "Airbnb",
            "Transaction": "EX85",
            "AccDate": "04-Nov-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "1371.67",
            "ExpAmntWthtoutVat": "1371.67",
            "TtlPmnt": "0.00",
            "BlncExp": "",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC53"
        }
    ]
}