
export const  Obj = 
{
    "Vat": [
        {
            "LstSave": "07-Nov-2019",
            "ExpWithVat": "10",
            "IncWithVat": "",
            "Transaction": "VT12",
            "From": "November-2019",
            "To": "November-2019",
            "PmntStts": "Fully paid",
            "TtlPmnt": "13364.28",
            "VatPayRtrn": "13364.28",
            "valueInc-Vat": "13373.37",
            "valueInc-withVat": "",
            "valueInc-withoutVat": "133733.7",
            "valuex-Vat": "9.09",
            "valuex-withVat": "10",
            "valuex-withoutVat": "90.91",
            "Fund": "",
            "BlncVat": "0"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpWithVat": "",
            "IncWithVat": "",
            "Transaction": "VT18",
            "From": "October-2019",
            "To": "November-2019",
            "PmntStts": "Unpaid",
            "TtlPmnt": "",
            "VatPayRtrn": "28039.39",
            "valueInc-Vat": "28087.94",
            "valueInc-withVat": "2000",
            "valueInc-withoutVat": "280879.4",
            "valuex-Vat": "48.55",
            "valuex-withVat": "122444.72",
            "valuex-withoutVat": "485.53",
            "Fund": "Miri Fund",
            "BlncVat": "28039.39"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpWithVat": "",
            "IncWithVat": "377184.16",
            "Transaction": "VT26",
            "From": "November-2019",
            "To": "December-2019",
            "PmntStts": "Partially paid",
            "TtlPmnt": "120",
            "VatPayRtrn": "37718.41",
            "valueInc-Vat": "37718.41",
            "valueInc-withVat": "",
            "valueInc-withoutVat": "377184.16",
            "valuex-Vat": "",
            "valuex-withVat": "117185.41",
            "valuex-withoutVat": "",
            "Fund": "SHMUELFUND",
            "BlncVat": "37598.41"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpWithVat": "",
            "IncWithVat": "15771.03",
            "Transaction": "VT27_213e695d-d136-4a75-aafb-7158be3964c4",
            "From": "November-2019",
            "To": "November-2019",
            "PmntStts": "Unpaid",
            "TtlPmnt": "0",
            "VatPayRtrn": "1577.1",
            "valueInc-Vat": "1577.1",
            "valueInc-withVat": "",
            "valueInc-withoutVat": "15771.03",
            "valuex-Vat": "",
            "valuex-withVat": "5147.34",
            "valuex-withoutVat": "",
            "Fund": "SHMUELFUND",
            "BlncVat": "1577.1"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpWithVat": "",
            "IncWithVat": "",
            "Transaction": "VT35_e6224d38-42e0-40c7-9011-cf13f4d3219f",
            "From": "December-2019",
            "To": "January-2020",
            "PmntStts": "Unpaid",
            "TtlPmnt": "",
            "VatPayRtrn": "579.88",
            "valueInc-Vat": "680.88",
            "valueInc-withVat": "",
            "valueInc-withoutVat": "6808.8",
            "valuex-Vat": "101",
            "valuex-withVat": "27350.81",
            "valuex-withoutVat": "1010",
            "Fund": "TEST",
            "BlncVat": "579.88"
        }
    ]
}