export const  ObjMngCommission = 
	  {
    "Management Expenses": [
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX102",
            "AccDatee": "20-Nov-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "660.27",
            "ExpAmntWthtoutVat": "660.27",
            "AmntWihtoutVat": "660.27",
            "TtlPmnt": "0",
            "BlncExp": "660.27",
            "CmsnVat": "660.27",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "asd",
            "RC": "RC61",
            "RsrvAmnt": "3301.33",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX110",
            "AccDatee": "30-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "222.22",
            "ExpAmntWthtoutVat": "222.22",
            "AmntWihtoutVat": "222.22",
            "TtlPmnt": "0",
            "BlncExp": "222.22",
            "CmsnVat": "222.22",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "new test rc75",
            "RC": "RC75",
            "RsrvAmnt": "1111.11",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX112",
            "AccDatee": "30-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "222.22",
            "ExpAmntWthtoutVat": "222.22",
            "AmntWihtoutVat": "222.22",
            "TtlPmnt": "0",
            "BlncExp": "222.22",
            "CmsnVat": "222.22",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "rc76",
            "RC": "RC76",
            "RsrvAmnt": "1111.11",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX114",
            "AccDatee": "30-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "222.22",
            "ExpAmntWthtoutVat": "222.22",
            "AmntWihtoutVat": "222.22",
            "TtlPmnt": "0",
            "BlncExp": "222.22",
            "CmsnVat": "222.22",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "RC77",
            "RC": "RC77",
            "RsrvAmnt": "1111.11",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "01-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX118",
            "AccDatee": "29-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "200",
            "ExpAmntWthtoutVat": "200.00",
            "AmntWihtoutVat": "200",
            "TtlPmnt": "0",
            "BlncExp": "200",
            "CmsnVat": "200",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "newtest",
            "RC": "RC80",
            "RsrvAmnt": "1000",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX123",
            "AccDatee": "10-Dec-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "47342.02",
            "ExpAmntWthtoutVat": "47342.02",
            "AmntWihtoutVat": "47342.02",
            "TtlPmnt": "0",
            "BlncExp": "47342.02",
            "CmsnVat": "47342.02",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "aaass",
            "RC": "RC108_7f0a2551-f8f9-4087-87a1-f4289a47fdb4",
            "RsrvAmnt": "236710.1",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "03-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX125",
            "AccDatee": "16-Dec-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "101572.06",
            "ExpAmntWthtoutVat": "101572.06",
            "AmntWihtoutVat": "101572.06",
            "TtlPmnt": "0",
            "BlncExp": "101572.06",
            "CmsnVat": "101572.06",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "fg",
            "RC": "RC109_7c447bca-7bed-4824-83d4-840be1e47fa2",
            "RsrvAmnt": "507860.29",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX127_e2176c7b-0cd6-46ec-b102-fa8b9099da0f",
            "AccDatee": "09-Dec-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "24940.61",
            "ExpAmntWthtoutVat": "24940.61",
            "AmntWihtoutVat": "24940.61",
            "TtlPmnt": "0",
            "BlncExp": "24940.61",
            "CmsnVat": "24940.61",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "zzzz",
            "RC": "RC110_72fdc530-9c7c-4f84-9682-c4aaf6f5b030",
            "RsrvAmnt": "124703.03",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "04-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX138_5fb26066-8c28-4e88-b53c-bd01ba58ac96",
            "AccDatee": "04-Feb-2020",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "222.22",
            "ExpAmntWthtoutVat": "222.22",
            "AmntWihtoutVat": "222.22",
            "TtlPmnt": "0",
            "BlncExp": "222.22",
            "CmsnVat": "222.22",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "testnow",
            "RC": "RC113_d69ebbe9-c256-4abd-a2cd-022d942d8bc6",
            "RsrvAmnt": "1111.11",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX140_cb49b8dd-e702-4984-8c09-d7f441fc7463",
            "AccDatee": "05-Dec-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "232.1",
            "ExpAmntWthtoutVat": "232.1",
            "AmntWihtoutVat": "232.1",
            "TtlPmnt": "0",
            "BlncExp": "232.1",
            "CmsnVat": "232.1",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "h",
            "RC": "RC114_db240972-7a11-45ff-a1bf-fdb44a7ed57d",
            "RsrvAmnt": "1160.48",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX143_ce77fc8f-e1ab-42d9-9e93-b659a04642c8",
            "AccDatee": "13-Dec-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "0",
            "ExpAmntWthtoutVat": "0",
            "AmntWihtoutVat": "0",
            "TtlPmnt": "0",
            "BlncExp": "0",
            "CmsnVat": "0",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "idan Lavy",
            "RC": "RC115_a11c1b03-3717-4ce9-8a4b-7396c8d69a72",
            "RsrvAmnt": "1010.1",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX145_afe1d062-f481-454d-877a-73865550c3a5",
            "AccDatee": "10-Dec-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "2222.22",
            "ExpAmntWthtoutVat": "2222.22",
            "AmntWihtoutVat": "2222.22",
            "TtlPmnt": "0",
            "BlncExp": "2222.22",
            "CmsnVat": "2222.22",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "fgfg",
            "RC": "RC117_926b7d87-3a25-47ab-b25c-4e265fc832ab",
            "RsrvAmnt": "11111.11",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX147_8ee9ddac-f578-4d7d-b641-cca1e379e5c5",
            "AccDatee": "01-Jan-2020",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "202.02",
            "ExpAmntWthtoutVat": "202.02",
            "AmntWihtoutVat": "202.02",
            "TtlPmnt": "0",
            "BlncExp": "202.02",
            "CmsnVat": "202.02",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST111",
            "RC": "RC118_aa122989-3e21-48f4-9434-9c0b1acb2ae5",
            "RsrvAmnt": "1010.1",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX149_4e64049e-c3ce-4851-b503-390c333d3173",
            "AccDatee": "23-Dec-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "927.64",
            "ExpAmntWthtoutVat": "927.64",
            "AmntWihtoutVat": "927.64",
            "TtlPmnt": "0",
            "BlncExp": "927.64",
            "CmsnVat": "927.64",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST2",
            "RC": "RC119_79fa8649-5730-48dd-ae21-aa9f6bea6b11",
            "RsrvAmnt": "4638.22",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "01-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX34",
            "AccDatee": "06-Nov-2019",
            "PrpName": "idanprop3",
            "AptName": "Idanprop3 Apartment",
            "Amnt": "204.08",
            "ExpAmntWthtoutVat": "185.53",
            "AmntWihtoutVat": "185.53",
            "TtlPmnt": "0",
            "BlncExp": "204.08",
            "CmsnVat": "204.08",
            "VatAmnt": "18.55",
            "CostType": "Variable Cost",
            "GstName": "TEST 1",
            "RC": "RC21",
            "RsrvAmnt": "927.64",
            "RsrvAmntDesc": "NoVat",
            "Vat": "TRUE"
        },
        {
            "LstSave": "18-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX37",
            "AccDatee": "04-Nov-2019",
            "PrpName": "idanprop3",
            "AptName": "Idanprop3 Apartment",
            "Amnt": "220",
            "ExpAmntWthtoutVat": "200",
            "AmntWihtoutVat": "200",
            "TtlPmnt": "0",
            "BlncExp": "220",
            "CmsnVat": "220",
            "VatAmnt": "20",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC22",
            "RsrvAmnt": "1000",
            "RsrvAmntDesc": "NoVat",
            "Vat": "TRUE"
        },
        {
            "LstSave": "01-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX54",
            "AccDatee": "12-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "36310.59",
            "ExpAmntWthtoutVat": "36310.59",
            "AmntWihtoutVat": "36310.59",
            "TtlPmnt": "0",
            "BlncExp": "36310.59",
            "CmsnVat": "36310.59",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "test3",
            "RC": "RC32",
            "RsrvAmnt": "181552.94",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "21-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX55",
            "AccDatee": "20-Nov-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "0",
            "ExpAmntWthtoutVat": "0",
            "AmntWihtoutVat": "0",
            "TtlPmnt": "0",
            "BlncExp": "0",
            "CmsnVat": "0",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "",
            "RC": "RC33",
            "RsrvAmnt": "90.91",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX61",
            "AccDatee": "26-Nov-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "994.48",
            "ExpAmntWthtoutVat": "994.48",
            "AmntWihtoutVat": "994.48",
            "TtlPmnt": "0",
            "BlncExp": "994.48",
            "CmsnVat": "994.48",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "test345",
            "RC": "RC38",
            "RsrvAmnt": "4972.38",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX63",
            "AccDatee": "18-Nov-2019",
            "PrpName": "TEST1",
            "AptName": "TEST AP1",
            "Amnt": "14824.33",
            "ExpAmntWthtoutVat": "14824.33",
            "AmntWihtoutVat": "14824.33",
            "TtlPmnt": "0",
            "BlncExp": "14824.33",
            "CmsnVat": "14824.33",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "zzzz",
            "RC": "RC39",
            "RsrvAmnt": "74121.66",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "07-Dec-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX64",
            "AccDatee": "21-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "200",
            "ExpAmntWthtoutVat": "200",
            "AmntWihtoutVat": "200",
            "TtlPmnt": "0",
            "BlncExp": "200",
            "CmsnVat": "200",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "gogo1",
            "RC": "RC40",
            "RsrvAmnt": "1000",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "30-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX70",
            "AccDatee": "27-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "22.47",
            "ExpAmntWthtoutVat": "22.47",
            "AmntWihtoutVat": "22.47",
            "TtlPmnt": "0",
            "BlncExp": "22.47",
            "CmsnVat": "22.47",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "Alanna Culingham",
            "RC": "RC43",
            "RsrvAmnt": "112.36",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX72",
            "AccDatee": "29-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "200",
            "ExpAmntWthtoutVat": "200.00",
            "AmntWihtoutVat": "200",
            "TtlPmnt": "0",
            "BlncExp": "200",
            "CmsnVat": "200",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST",
            "RC": "RC45",
            "RsrvAmnt": "1000",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX73",
            "AccDatee": "04-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "400",
            "ExpAmntWthtoutVat": "400.00",
            "AmntWihtoutVat": "400",
            "TtlPmnt": "0",
            "BlncExp": "400",
            "CmsnVat": "400",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "TEST2",
            "RC": "RC46",
            "RsrvAmnt": "2000",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX75",
            "AccDatee": "26-Jan-2020",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "284.76",
            "ExpAmntWthtoutVat": "284.76",
            "AmntWihtoutVat": "284.76",
            "TtlPmnt": "0",
            "BlncExp": "284.76",
            "CmsnVat": "284.76",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "Tulio valenzuela",
            "RC": "RC47",
            "RsrvAmnt": "1423.8",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX77",
            "AccDatee": "03-Dec-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "204.08",
            "ExpAmntWthtoutVat": "204.08",
            "AmntWihtoutVat": "204.08",
            "TtlPmnt": "0",
            "BlncExp": "204.08",
            "CmsnVat": "204.08",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "dfgdf",
            "RC": "RC48",
            "RsrvAmnt": "1020.41",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX80",
            "AccDatee": "22-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP1",
            "Amnt": "20000",
            "ExpAmntWthtoutVat": "20000.00",
            "AmntWihtoutVat": "20000",
            "TtlPmnt": "0",
            "BlncExp": "20000",
            "CmsnVat": "20000",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "dgfdgd",
            "RC": "RC50",
            "RsrvAmnt": "100000",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX81",
            "AccDatee": "15-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "1020.41",
            "ExpAmntWthtoutVat": "1020.41",
            "AmntWihtoutVat": "1020.41",
            "TtlPmnt": "0",
            "BlncExp": "1020.41",
            "CmsnVat": "1020.41",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "gfgf",
            "RC": "RC51",
            "RsrvAmnt": "5102.04",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX84",
            "AccDatee": "29-Nov-2019",
            "PrpName": "IDANPROP1",
            "AptName": "IDANAP2",
            "Amnt": "20408.16",
            "ExpAmntWthtoutVat": "20408.16",
            "AmntWihtoutVat": "20408.16",
            "TtlPmnt": "0",
            "BlncExp": "20408.16",
            "CmsnVat": "20408.16",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "dfgdfd",
            "RC": "RC52",
            "RsrvAmnt": "102040.82",
            "RsrvAmntDesc": "YesVat",
            "Vat": "FALSE"
        },
        {
            "LstSave": "29-Nov-2019",
            "ExpType": "Management commission",
            "vendor": "Idan's Company",
            "Transaction": "EX86",
            "AccDatee": "04-Nov-2019",
            "PrpName": "SHMUELPROP1",
            "AptName": "SHMUELAP1",
            "Amnt": "2493.94",
            "ExpAmntWthtoutVat": "2493.94",
            "AmntWihtoutVat": "2493.94",
            "TtlPmnt": "0",
            "BlncExp": "2493.94",
            "CmsnVat": "2493.94",
            "VatAmnt": "0",
            "CostType": "Variable Cost",
            "GstName": "aaa",
            "RC": "RC53",
            "RsrvAmnt": "12469.7",
            "RsrvAmntDesc": "NoVat",
            "Vat": "FALSE"
        }
    ]
}